[2022-12-07T10:50:11.533+0000] {processor.py:153} INFO - Started process (PID=44) to work on /opt/airflow/dags/ticketsim.py
[2022-12-07T10:50:11.543+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ticketsim.py for tasks to queue
[2022-12-07T10:50:11.544+0000] {logging_mixin.py:137} INFO - [2022-12-07T10:50:11.543+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ticketsim.py
[2022-12-07T10:50:11.556+0000] {logging_mixin.py:137} INFO - [2022-12-07T10:50:11.555+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ticketsim.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ticketsim.py", line 15, in <module>
    "EXECUTION_DATETIME_STR": EXECUTION_DATETIME_STR
NameError: name 'EXECUTION_DATETIME_STR' is not defined
[2022-12-07T10:50:11.557+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ticketsim.py
[2022-12-07T10:50:11.607+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ticketsim.py took 0.078 seconds
[2022-12-07T10:50:42.074+0000] {processor.py:153} INFO - Started process (PID=106) to work on /opt/airflow/dags/ticketsim.py
[2022-12-07T10:50:42.074+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ticketsim.py for tasks to queue
[2022-12-07T10:50:42.075+0000] {logging_mixin.py:137} INFO - [2022-12-07T10:50:42.075+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ticketsim.py
[2022-12-07T10:50:42.077+0000] {logging_mixin.py:137} INFO - [2022-12-07T10:50:42.076+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ticketsim.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ticketsim.py", line 15, in <module>
    "EXECUTION_DATETIME_STR": EXECUTION_DATETIME_STR
NameError: name 'EXECUTION_DATETIME_STR' is not defined
[2022-12-07T10:50:42.077+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ticketsim.py
[2022-12-07T10:50:42.100+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ticketsim.py took 0.029 seconds
[2022-12-07T10:51:12.239+0000] {processor.py:153} INFO - Started process (PID=170) to work on /opt/airflow/dags/ticketsim.py
[2022-12-07T10:51:12.243+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ticketsim.py for tasks to queue
[2022-12-07T10:51:12.244+0000] {logging_mixin.py:137} INFO - [2022-12-07T10:51:12.244+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ticketsim.py
[2022-12-07T10:51:12.247+0000] {logging_mixin.py:137} INFO - [2022-12-07T10:51:12.246+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ticketsim.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ticketsim.py", line 15, in <module>
    "EXECUTION_DATETIME_STR": EXECUTION_DATETIME_STR
NameError: name 'EXECUTION_DATETIME_STR' is not defined
[2022-12-07T10:51:12.248+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ticketsim.py
[2022-12-07T10:51:12.277+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ticketsim.py took 0.041 seconds
[2022-12-07T10:51:43.246+0000] {processor.py:153} INFO - Started process (PID=245) to work on /opt/airflow/dags/ticketsim.py
[2022-12-07T10:51:43.247+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ticketsim.py for tasks to queue
[2022-12-07T10:51:43.247+0000] {logging_mixin.py:137} INFO - [2022-12-07T10:51:43.247+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ticketsim.py
[2022-12-07T10:51:43.249+0000] {logging_mixin.py:137} INFO - [2022-12-07T10:51:43.248+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ticketsim.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ticketsim.py", line 15, in <module>
    "EXECUTION_DATETIME_STR": EXECUTION_DATETIME_STR
NameError: name 'EXECUTION_DATETIME_STR' is not defined
[2022-12-07T10:51:43.249+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ticketsim.py
[2022-12-07T10:51:43.274+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ticketsim.py took 0.031 seconds
